import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { MainProvider } from "@/providers/main-provider";
import { ThemeToggleButton } from "@/components/theme-toggle-button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" suppressHydrationWarning>
      <body className={inter.className}>
        <MainProvider>
          <header className="p-9">
            <ThemeToggleButton />
          </header>
          <main>{children}</main>
        </MainProvider>
      </body>
    </html>
  );
}
